AllCops:
  DisplayCopNames: true

Lint/UnneededDisable:
  Enabled: false

Metrics:
  Severity: warning

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Metrics/LineLength:
  Max: 160
Metrics/CyclomaticComplexity:
  Max: 10

Style/FormatString:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Style/Encoding:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Style/AndOr:
  Enabled: false
